### ISSUE TITLE
Markdown text from WP XML stripped off line breaks

### ISSUE THREAD

**Issue by rollbahn** [palaniraja/blog2md#13]
I have been testing Hugo and decided to dump out my WP posts which number close to 5000. I ran blog2md on the XML file and everything went very well except when I checked the md files.

All the post data is correct except for the body of the post, which is stripped of all linebreaks for the paragraphs.

I tried poking around in the index.js to see why but couldn't see anything obvious.

My WP posts are all in Markdown so I am wondering if your code is expecting HTML instead.

Here's a screenshot of the WP XML file followed by what it looks like after blog2md:

![Screen Shot 2019-11-21 at 2 32 27 pm](https://user-images.githubusercontent.com/376430/69304277-c7b84e00-0c6b-11ea-8fe5-e2691275e736.jpg)

![Screen Shot 2019-11-21 at 2 34 02 pm](https://user-images.githubusercontent.com/376430/69304360-0fd77080-0c6c-11ea-9738-abd578ddbaba.jpg)

Thanks for your help.

**Comment by jaredmo** [comment]
I had the same issue.

**Comment by JamesSkemp** [comment]
I also ran into this for some percentage of our posts.

Digging into it, this is due to how turndown works. See https://github.com/domchristie/turndown/issues/264

There's a linked merge request for another project that includes a fix: https://github.com/hexojs/hexo-migrator-wordpress/pull/79/files

More than happy to submit a merge request with an argument switch, but here's what I changed to support this:

```diff
@@ -170,7 +170,12 @@ function wordpressImport(backupXmlFile, outputDir){

                     if (post["content:encoded"]){
                         // console.log('content available');
-                        content = '<div>'+post["content:encoded"]+'</div>'; //to resolve error if plain text returned
+                        var postContent = post["content:encoded"].toString();
+                        if (!/<p>/i.test(postContent)) {
+                            postContent = '<p>' + postContent.replace(/(\r?\n){2}/g, '</p>\n\n<p>') + '</p>';
+                        }
+
+                        content = '<div>'+postContent+'</div>'; //to resolve error if plain text returned
                         markdown = tds.turndown(content);
```

**Comment by palaniraja** [comment]
@JamesSkemp  yes, please submit a merge request and include this with as an argument switch.
